SENSORY = [
  "Do you feel tingling in your feet?",
  "Do you feel tingling in your hands?",
  "Do you experience a burning sensation in your feet?",
  "Do you experience a burning sensation in your hands?",
  "Do you feel sharp, stabbing pain in your toes?",
  "Do you feel electric shock-like sensations in your limbs?",
  "Do you have numbness in your feet?",
  "Do you have numbness in your hands?",
  "Do you feel pins and needles in your extremities?",
  "Do you feel crawling sensations under your skin?",
  "Do you experience oversensitivity to touch (e.g., clothing, bedsheets)?",
  "Do you have a reduced ability to feel temperature changes?",
  "Do you have a reduced ability to feel pain?",
  "Do your feet or hands feel like you're wearing socks or gloves when you're not?",
  "Do your feet ache at night?",
  "Do you have intermittent shooting pains in your legs or feet?",
  "Do your feet feel cold even when they are not?",
  "Do your feet feel hot even when they are not?",
  "Are your toes hypersensitive to touch?",
  "Does your foot pain worsen at night?",
  "Does pain improve when you move or walk?",
  "Do you feel dry, cracked skin on your feet?",
  "Do you have trouble feeling vibrations in your feet?",
  "Do you struggle to detect pressure changes under your feet?",
  "Do your feet feel swollen when they are not?",
  "Do you experience prickly or buzzing sensations?",
  "Do you feel like you're walking on pebbles or sand?",
  "Do you have difficulty feeling textures like carpet or sand?",
  "Is your response to pain or heat slower than usual?",
  "Does cold weather worsen your tingling symptoms?",
  "Do you experience pain from light touch?",
  "Do bedsheets cause discomfort to your feet?",
  "Do your shoes cause pain even when properly fitted?",
  "Do you often feel foot discomfort in closed shoes?",
  "Have you missed injuries or cuts on your feet due to reduced feeling?",
  "Does pain spread from your toes upward?",
  "Do your feet feel itchy without a clear cause?",
  "Do you feel uncomfortable when getting a foot massage?",
  "Do you have a dull, persistent ache in your feet?",
  "Do your feet feel tingly after sitting for a while?"
] 

MOTOR = [
  "Do you experience muscle weakness in your feet?",
  "Do you frequently have foot or leg cramps?",
  "Do you have difficulty lifting your foot while walking (foot drop)?",
  "Do you have trouble climbing stairs?",
  "Do you find it difficult to hold or lift small objects?",
  "Do your lower legs feel tired or fatigued?",
  "Do you struggle to flex or wiggle your toes?",
  "Do you experience muscle twitching in your legs or feet?",
  "Has the arch of your foot changed or flattened over time?",
  "Do you feel a decrease in your grip strength?",
  "Do you have trouble with fine hand coordination (e.g., buttoning clothes)?",
  "Do your ankles feel weak or unstable?",
  "Have you noticed changes in how you walk?",
  "Do your legs feel heavy or unresponsive?",
  "Have your toes started to curl or claw?",
  "Do you feel unstable while walking?",
  "Do your hands or feet tremble at rest?",
  "Do you have difficulty pushing off the ground while walking?",
  "Do your shoes wear unevenly due to altered walking posture?",
  "Do you have trouble standing on your heels or toes?"
]

AUTONOMIC = [
  "Do your feet sweat excessively?",
  "Do your feet sweat less than usual?",
  "Do your feet feel cold and dry even in warm weather?",
  "Have you experienced sexual dysfunction?",
  "Do you have difficulty maintaining an erection (men)?",
  "Do you experience vaginal dryness (women)?",
  "Do you frequently feel the need to urinate?",
  "Do you feel like you can't completely empty your bladder?",
  "Do you suffer from constipation?",
  "Do you experience unexplained diarrhea (especially at night)?",
  "Do you feel bloated after meals?",
  "Has your digestion become slower than usual?",
  "Do you feel nauseous after eating?",
  "Have you vomited undigested food?",
  "Do you feel full quickly while eating small amounts?",
  "Do you get dizzy or lightheaded when standing up?",
  "Is your resting heart rate unusually high?",
  "Do you suffer from dry eyes?",
  "Do you have a persistently dry mouth?",
  "Do you feel your pupils react abnormally to light (too slow or too fast)?",
  "Do you struggle with night vision?",
  "Do your blood sugar levels fluctuate more than expected?",
  "Do you stop sweating during physical activity?",
  "Do you experience a reduced sense of hunger or thirst?"
] 

FUNCTIONAL = [
  "Do you trip or fall more frequently than you used to?",
  "Do you have difficulty maintaining balance?",
  "Are you afraid to walk barefoot due to numbness or pain?",
  "Do you find it difficult to drive due to foot sensitivity?",
  "Do your symptoms disturb your sleep?",
  "Do you wake up at night due to foot discomfort?",
  "Do you feel less confident walking in the dark?",
  "Do you avoid certain surfaces like gravel or stairs?",
  "Do you have trouble feeling the brake or gas pedals while driving?",
  "Do you find it harder to walk on uneven surfaces?",
  "Have you noticed changes in your gait or walking style?",
  "Do you experience fatigue after short walks?",
  "Do you feel unsteady even when standing still?",
  "Do you need to look at your feet while walking?",
  "Do you avoid physical activity due to foot discomfort?",
  "Have you reduced your daily activities because of foot symptoms?"
]